### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by andrew** [ecosyste-ms/documentation#153]
To help explain what/why/how etc on the front door of the project so that people discovering the project can quickly get up to speed on things. Improvements like:

- more description of the history and reasons the project exists
- how to use the projects
- how to contribute to the projects
- what the plans for the future are for the project.
- who uses the project

<a href="https://dashboard.polar.sh/ecosyste-ms/home/issues/153">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/ecosyste-ms/home/issues/153/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/ecosyste-ms/home/issues/153/pledge.svg">
</picture>
</a>

**Comment by sdruskat** [comment]
Hi @andrew 👋,

As the projects are now used in academic research, perhaps including citation information (e.g., via a [`CITATION.cff`](https://citation-file-format.github.io/) file) would be useful?
[cffinit](https://citation-file-format.github.io/cff-initializer-javascript/#/) is a simple web form app that can produce valid CFF files.

**Comment by andrew** [comment]
@sdruskat yes! I'll get that added to all repos now

**Comment by andrew** [comment]
@sdruskat https://github.com/ecosyste-ms/home/commit/8f901887864b055a39c852a743c8618c8a2835f5

**Comment by andrew** [comment]
I've done it for all the main repos now, thanks for the reminder
